### PR TITLE
adding foreground helper

### PR DESCRIPTION
**Pull request by goozbach**
there's a background helper, why not a foreground?

### CODE REVIEW

**Comment by geraldb** [comment]
Great. How would you use it? For images? Sorry the ignorance. Is there such as thing as a foreground css property? Thanks for any clarification. Cheers.

**Comment by goozbach** [comment]
I'm using it like this:

```
{{ background #444 }}
{{ foreground #aaa }}
```

To make light colored text show up on a dark background.

As far as the CSS property it is 'color', should I change the keyword to that?

**Comment by geraldb** [comment]
Thanks. Might be easier to use if it matches the CSS property e.g. color. Cheers.

**Comment by geraldb** [comment]
You're invited to make your helper(s) into a plugin for download. See [Analytics](https://github.com/slideshow-s9/analytics) or [Tables](https://github.com/slideshow-s9/tables) for examples. Keep it up. Cheers.

**Pull request closed without merging**
